version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - inference-server
    restart: unless-stopped

  inference-server:
    build: .
    environment:
      - TRANSFORMERS_CACHE=/app/cache
      - HF_HOME=/app/cache
    volumes:
      - model_cache:/app/cache
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  model_cache:
